[package]
name = "crabmole"
version = "0.0.2"
edition = "2021"
license = "MIT OR Apache-2.0 OR BSD-3-Clause"
description = "Porting Go standard library in Rust"
documentation = "https://docs.rs/crabmole/"
homepage = "https://github.com/al8n/crabmole"
repository = "https://github.com/al8n/crabmole"

[features]
default = ["std"]
full = ["std", "sort"]
std = ["alloc"]
alloc = []

sort = []

[dependencies]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

