[package]
name = "crabmole"
version = "0.0.1"
edition = "2021"
license = "MIT/Apache-2.0/BSD-3-Clause"
description = "Porting Go standard library in Rust"
repository = "https://github.com/al8n/crabmole"

[features]
default = ["std"]
full = ["std", "sort"]
std = ["alloc"]
alloc = []

sort = []


[dependencies]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

